# API BASE URL
@api = https://localhost:8081/httpbin

# REQUESTS
GET {{api}}/get
api-key: {{api-key}}
ocp-apim-trace: true
###
POST {{api}}/post
Content-Type: application/json
api-key: {{api-key}}
ocp-apim-trace: true

{
    "Location": "Ready 2020",
    "time": "{{$localDatetime rfc1123}}"
}
###
GET {{api}}/status/418
api-key: {{api-key}}
ocp-apim-trace: true
###
GET {{api}}/delay/2
api-key: {{api-key}}
ocp-apim-trace: true

# TO ENABLE TRACING
# api-key: {{api-key}}
# ocp-apim-trace: true

