apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name:
        # create a volume linked to the pvc below and mount it in the container
        volumeMounts:
          - mountPath: /apim/config
            name: private-gateway-volume
      volumes:
        - name: private-gateway-volume
          persistentVolumeClaim:
              claimName: private-gateway-pvc
---
# This claim binds to an existing or dynamically created persistent volume of sufficient size and default
# StorageClass if one is configured for the cluster.
# Consider explicitly defining persistent volume following best practices for your Kubernetes environment.
# Go to https://kubernetes.io/docs/concepts/storage/ to learn about storage in Kubernetes.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-gateway-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi # Feel free to adjust up to avoid running out of space