# NOTE: Before deploying into production please review documentation -> https://aka.ms/self-hosted-gateway-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env
data:
  config.service.endpoint: "https://one.management.azure-api.net/subscriptions/c6a33fd3-e442-48a4-b82d-bcc4ad8a71d7/resourcegroups/vlvinogr-apim/providers/Microsoft.ApiManagement/service/one?api-version=2019-12-01"
  telemetry.metrics.local: "statsd"
  telemetry.metrics.local.statsd.endpoint: "statsd.telemetry:8125"
  telemetry.metrics.local.statsd.sampling: "1"
  telemetry.metrics.local.statsd.tag-format: "dogStatsD"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "gateway-app"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: gateway
        image: mcr.microsoft.com/azure-api-management/gateway:beta
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /internal-status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: gateway-token
              key: value
        envFrom:
        - configMapRef:
            name: gateway-env
        volumeMounts:
          - mountPath: /apim/config
            name: private-gateway-volume
      volumes:
        - name: private-gateway-volume
          persistentVolumeClaim:
              claimName: private-gateway-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: gateway
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-gateway-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi # Feel free to adjust up to avoid running out of space