apiVersion: v1
kind: Pod
metadata:
  name: sleepy-pod
spec:
  containers:
    - name: sleepy
      image: alpine:latest
      command: ["/bin/sh","-c"]
      args: ["apk add --update curl; sleep 3600"]
